'use client';
import {useEffect,useState} from 'react';
const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:8000/api';
type Team={id:number;name:string;abbreviation:string;conference:string;division:string};
type Save={id:number;name:string;day:number;season:number;user_team:Team};
type Standing={team:string;games:number;wins:number;losses:number;otl:number;points:number;gf:number;ga:number};
export default function Home(){
 const [teams,setTeams]=useState<Team[]>([]),[saves,setSaves]=useState<Save[]>([]),[active,setActive]=useState<Save|null>(null),[standings,setStandings]=useState<Standing[]>([]),[teamId,setTeamId]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{Promise.all([fetch(`${API}/teams`).then(r=>r.json()),fetch(`${API}/saves`).then(r=>r.json())]).then(([t,s])=>{setTeams(t);setTeamId(String(t[0]?.id||''));setSaves(s);setActive(s[0]||null)})},[]);
 useEffect(()=>{if(active)fetch(`${API}/saves/${active.id}/standings`).then(r=>r.json()).then(setStandings)},[active]);
 async function create(){const r=await fetch(`${API}/saves`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'Ny karriär',team_id:+teamId})});const s=await r.json();setActive(s);setSaves([s,...saves])}
 async function simulate(){if(!active)return;setBusy(true);const r=await fetch(`${API}/saves/${active.id}/simulate`,{method:'POST'}).then(r=>r.json());setActive({...active,day:r.day});setStandings(await fetch(`${API}/saves/${active.id}/standings`).then(r=>r.json()));setBusy(false)}
 return <main className="min-h-screen">
  <header className="border-b border-white/10 bg-navy/90 px-6 py-4"><div className="mx-auto flex max-w-7xl items-center justify-between"><div><p className="text-xs font-bold tracking-[.3em] text-lime">HOCKEY OPERATIONS</p><h1 className="text-2xl font-black">PUCK DYNASTY</h1></div><span className="rounded-full border border-lime/40 px-3 py-1 text-xs text-lime">LOCAL CAREER</span></div></header>
  <div className="mx-auto grid max-w-7xl gap-6 p-6 lg:grid-cols-[230px_1fr]">
   <aside className="rounded-2xl border border-white/10 bg-white/5 p-4"><p className="mb-3 text-xs font-bold uppercase text-slate-400">Ny karriär</p><select aria-label="Välj lag" className="w-full rounded-lg p-2" value={teamId} onChange={e=>setTeamId(e.target.value)}>{teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><button onClick={create} className="mt-3 w-full rounded-lg bg-lime p-2 font-bold text-navy">Starta save</button><p className="mb-2 mt-8 text-xs font-bold uppercase text-slate-400">Sparfiler</p>{saves.map(s=><button key={s.id} onClick={()=>setActive(s)} className="mb-2 w-full rounded-lg bg-white/5 p-2 text-left text-sm hover:bg-white/10">{s.name}<span className="block text-xs text-slate-400">{s.user_team.abbreviation} · Dag {s.day}</span></button>)}</aside>
   <section>{active?<><div className="mb-6 grid gap-4 md:grid-cols-3"><Card label="DIN KLUBB" value={active.user_team.name}/><Card label="SÄSONG" value={`${active.season}–${active.season+1}`}/><div className="rounded-2xl bg-lime p-5 text-navy"><p className="text-xs font-bold">NÄSTA STEG · DAG {active.day}</p><button disabled={busy} onClick={simulate} className="mt-2 text-xl font-black">{busy?'SIMULERAR…':'SIMULERA MATCHDAG →'}</button></div></div><div className="overflow-hidden rounded-2xl border border-white/10 bg-white/5"><div className="flex items-center justify-between border-b border-white/10 p-5"><h2 className="text-xl font-black">LEAGUE STANDINGS</h2><span className="text-xs text-slate-400">AUTO-SAVED</span></div><table className="w-full text-sm"><thead className="bg-white/5 text-slate-400"><tr>{['#','LAG','GP','W','L','OT','PTS','DIFF'].map(x=><th key={x} className="p-3 text-left">{x}</th>)}</tr></thead><tbody>{standings.map((s,i)=><tr key={s.team} className="border-t border-white/5"><td className="p-3 text-slate-500">{i+1}</td><td className="p-3 font-bold">{s.team}</td><td>{s.games}</td><td>{s.wins}</td><td>{s.losses}</td><td>{s.otl}</td><td className="font-bold text-lime">{s.points}</td><td>{s.gf-s.ga>0?'+':''}{s.gf-s.ga}</td></tr>)}</tbody></table></div></>:<div className="grid min-h-[65vh] place-items-center rounded-2xl border border-dashed border-white/20"><div className="text-center"><p className="text-5xl">🏒</p><h2 className="mt-4 text-3xl font-black">BYGG DIN DYNASTI</h2><p className="mt-2 text-slate-400">Välj ett av 32 lag och starta din första karriär.</p></div></div>}</section>
  </div></main>}
function Card({label,value}:{label:string,value:string}){return <div className="rounded-2xl border border-white/10 bg-white/5 p-5"><p className="text-xs font-bold text-slate-400">{label}</p><p className="mt-2 text-xl font-black">{value}</p></div>}
