let state,page='overview';const $=s=>document.querySelector(s),money=n=>new Intl.NumberFormat('sv-SE',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n||0);
async function load(){state=await fetch('/api/state').then(r=>r.json());renderShell();render()}
function renderShell(){let s=state.simulation;$('#date').textContent=s?.simulation_date||'Ingen simulation';$('#phase').textContent=`${s?.season||'—'} · ${s?.phase||'—'} · Dag ${s?.day||0}`;$('#cap').textContent=money(state.cap.cap_space);$('#size').textContent=state.cap.active_players??state.roster.length;$('#unread').textContent=state.inbox.filter(x=>x.status==='UNREAD').length;$('#nav').innerHTML=state.nav.map(n=>`<button data-page="${n.id}" class="${page===n.id?'active':''}">${n.label}</button>`).join('');document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{page=b.dataset.page;renderShell();render()})}
const card=(title,value,sub,target)=>`<article class="card click" data-target="${target}"><span class="muted">${title}</span><div class="value">${value}</div><span class="muted">${sub}</span></article>`;
function overview(){return `<h1>God morgon, General Manager</h1><p class="subtitle">Ditt kontrollrum för Edmonton Oilers · Nästa deadline: Free agency</p><div class="grid">${card('CAP SPACE',money(state.cap.cap_space),`${money(state.cap.total_cap_charge)} belastning`,'cap')}${card('AKTIV ROSTER',state.roster.filter(x=>x.level==='NHL').length,'Max 23 spelare','roster')}${card('OLÄSTA BESLUT',state.inbox.filter(x=>x.status==='UNREAD').length,'Inkorg och erbjudanden','inbox')}${card('DATASTATUS',state.audit.ok?'Godkänd':'Åtgärd krävs',`${state.audit.failures?.length||0} verifieringspunkter`,'settings')}<article class="card wide"><h2>Prioriterade GM-åtgärder</h2>${state.inbox.slice(0,4).map(x=>`<p><span class="tag">${x.priority}</span> <b>${x.subject}</b><br><span class="muted">${x.sender}</span></p>`).join('')}</article><article class="card wide"><h2>Senaste nytt</h2>${state.news.slice(0,4).map(x=>`<p><b>${x.headline}</b><br><span class="muted">${x.kind}</span></p>`).join('')}</article></div>`}
function roster(level='NHL'){let rs=state.roster.filter(x=>x.level===level);return `<h1>${level==='NHL'?'Trupp':'Farmarlag'}</h1><p class="subtitle">Verklig baslinje kopierad till isolerat simulationstillstånd.</p><div class="toolbar"><input id="search" placeholder="Sök spelare"><select id="pos"><option value="">Alla positioner</option><option>F</option><option>D</option><option>G</option></select></div><table><thead><tr><th>#</th><th>Spelare</th><th>Pos</th><th>Status</th><th>Moral</th><th>Form</th><th>Åtgärder</th></tr></thead><tbody>${rs.map(p=>`<tr data-name="${p.full_name.toLowerCase()}" data-pos="${p.primary_position}"><td>${p.jersey_number||'—'}</td><td><span class="link" data-player="${p.id}">${p.full_name}</span></td><td>${p.primary_position||'UNKNOWN'}</td><td><span class="tag">${p.status}</span></td><td>${p.morale}</td><td>${p.form}</td><td class="actions"><button onclick="act('${p.id}','${level==='NHL'?'AHL':'NHL'}')">${level==='NHL'?'Till AHL':'Kalla upp'}</button><button onclick="act('${p.id}','TRADE_BLOCK')">Trade block</button><button onclick="act('${p.id}','WAIVERS')">Waivers</button></td></tr>`).join('')}</tbody></table>`}
function inbox(){return `<h1>Inkorg</h1><p class="subtitle">Beslut uppdaterar simulationens händelselogg.</p><div class="grid">${state.inbox.map(m=>`<article class="card wide"><span class="tag">${m.priority}</span><h2>${m.subject}</h2><p class="muted">${m.sender} · ${m.category}</p><p>${m.content}</p><div class="actions">${JSON.parse(m.actions).map(a=>`<button onclick="msg(${m.id},'${a}')">${a}</button>`).join('')}</div></article>`).join('')}</div>`}
function generic(){let label=state.nav.find(x=>x.id===page)?.label;let data=page==='news'?state.news:page==='gms'?state.gms:page==='teams'?state.teams:page==='draft'?state.draft:[];return `<h1>${label}</h1><p class="subtitle">Databasansluten modul · simulation ${state.simulation?.id?.slice(0,8)||'—'}</p>${data.length?`<table><tbody>${data.map(x=>`<tr>${Object.values(x).slice(0,7).map(v=>`<td>${v??'UNKNOWN'}</td>`).join('')}</tr>`).join('')}</tbody></table>`:`<div class="card"><h2>Inga verifierade poster ännu</h2><p class="muted">UNKNOWN — DATA VERIFICATION REQUIRED. Modulen är aktiv och fylls av synk- eller simulationshändelser; inga fakta fabriceras.</p></div>`}`}
function cap(){return `<h1>Lönetak</h1><p class="subtitle">Beräknas alltid från aktiva roster- och kontraktsposter.</p><div class="grid">${Object.entries(state.cap).map(([k,v])=>card(k.replaceAll('_',' ').toUpperCase(),typeof v==='number'?money(v):String(v),'Datadrivet','cap')).join('')}</div>`}
function render(){let label=state.nav.find(x=>x.id===page)?.label||'Översikt';$('#crumb').textContent=label;$('#content').innerHTML=page==='overview'?overview():page==='roster'?roster():page==='ahl'?roster('AHL'):page==='inbox'?inbox():page==='cap'?cap():generic();document.querySelectorAll('[data-target]').forEach(x=>x.onclick=()=>{page=x.dataset.target;renderShell();render()});let q=$('#search'),p=$('#pos');if(q)for(let e of[q,p])e.oninput=()=>document.querySelectorAll('tbody tr').forEach(r=>r.hidden=!r.dataset.name.includes(q.value.toLowerCase())||(p.value&&!r.dataset.pos.includes(p.value)))}
async function post(url,body={}){let r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)alert((await r.json()).error);await load()}
async function act(player_id,action){if(confirm(`Bekräfta ${action}?`))await post('/api/roster-action',{player_id,action})}async function msg(id,action){await post(`/api/inbox/${id}`,{action})}$('#advance').onclick=()=>post('/api/advance');load();
